version: '3.8'
services:
    bot:
        image: debtbot-bot
        container_name: debtbot-bot
        build:
            context: ./bot
            dockerfile: ./bot.Dockerfile
        tty: true
        depends_on:
            - backend
            - db
    backend:
        image: debtbot-backend
        container_name: debtbot-backend
        build:
            context: ./backend
            dockerfile: ./backend.Dockerfile
        tty: true
        ports:
            - '8787:8787'
        environment:
            - DATABASE_URL=${DATABASE_URL}
        depends_on:
            - db
    db:
        image: mysql:8.3.0
        container_name: debtbot-db
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - TZ=${TZ}
        volumes:
            - ./my.cnf:/etc/mysql/conf.d/my.cnf
